// Repository Manager - Clone, Branch, Commit, Push, PR

import { octokit, getDefaultBranch } from "./githubClient.js";
import simpleGit, { SimpleGit } from "simple-git";
import path from "path";
import fs from "fs";

const TMP_DIR = path.join(process.cwd(), "tmp");

// Ensure tmp directory exists
function ensureTmpDir() {
  if (!fs.existsSync(TMP_DIR)) {
    fs.mkdirSync(TMP_DIR, { recursive: true });
  }
}

// Parse repo URL to owner/repo
function parseRepoUrl(repoUrl: string): { owner: string; repo: string } {
  const cleaned = repoUrl
    .replace("https://github.com/", "")
    .replace("git@github.com:", "")
    .replace(".git", "");
  const [owner, repo] = cleaned.split("/");
  return { owner, repo };
}

// Clone repository
export async function cloneRepo(repoUrl: string, jobId: string): Promise<string> {
  ensureTmpDir();
  const dir = path.join(TMP_DIR, jobId);

  // Clean up if exists
  if (fs.existsSync(dir)) {
    fs.rmSync(dir, { recursive: true, force: true });
  }

  const git = simpleGit();
  const authUrl = repoUrl.replace(
    "https://github.com/",
    `https://${process.env.GITHUB_TOKEN}@github.com/`
  );

  console.log(`[Git] Cloning repo to: ${dir}`);
  await git.clone(authUrl, dir);

  return dir;
}

// Create and checkout new branch
export async function createBranch(repoDir: string, branch: string): Promise<void> {
  const git: SimpleGit = simpleGit(repoDir);
  console.log(`[Git] Creating branch: ${branch}`);
  await git.checkoutLocalBranch(branch);
}

// Write files and commit
export async function commitFiles(
  repoDir: string,
  files: { path: string; content: string }[],
  message: string = "AutoIntegrate: injected integration templates"
): Promise<void> {
  const git: SimpleGit = simpleGit(repoDir);

  // Write all files
  for (const file of files) {
    const filePath = path.join(repoDir, file.path);
    const fileDir = path.dirname(filePath);

    // Ensure directory exists
    if (!fs.existsSync(fileDir)) {
      fs.mkdirSync(fileDir, { recursive: true });
    }

    fs.writeFileSync(filePath, file.content);
    console.log(`[Git] Wrote file: ${file.path}`);
  }

  // Stage and commit
  await git.add(".");
  await git.commit(message);
  console.log(`[Git] Committed ${files.length} files`);
}

// Push branch to remote
export async function pushBranch(repoDir: string, branch: string): Promise<void> {
  const git: SimpleGit = simpleGit(repoDir);
  console.log(`[Git] Pushing branch: ${branch}`);
  await git.push("origin", branch, ["--set-upstream"]);
}

// Create Pull Request
export async function createPR(
  repoUrl: string,
  branch: string,
  title: string = "AutoIntegrate: Add Integration Templates",
  body: string = "This PR was automatically generated by AutoIntegrate."
): Promise<string> {
  const { owner, repo } = parseRepoUrl(repoUrl);
  const defaultBranch = await getDefaultBranch(owner, repo);

  console.log(`[Git] Creating PR: ${branch} -> ${defaultBranch}`);

  const { data: pr } = await octokit.pulls.create({
    owner,
    repo,
    head: branch,
    base: defaultBranch,
    title,
    body,
  });

  console.log(`[Git] PR created: ${pr.html_url}`);
  return pr.html_url;
}

// Cleanup temp directory
export async function cleanupRepo(jobId: string): Promise<void> {
  const dir = path.join(TMP_DIR, jobId);
  if (fs.existsSync(dir)) {
    fs.rmSync(dir, { recursive: true, force: true });
    console.log(`[Git] Cleaned up: ${dir}`);
  }
}

// Full git workflow
export async function fullGitWorkflow(
  repoUrl: string,
  jobId: string,
  files: { path: string; content: string }[]
): Promise<string> {
  const branch = `autointegrate/${jobId}`;

  // Step 1: Clone
  const repoDir = await cloneRepo(repoUrl, jobId);

  // Step 2: Create branch
  await createBranch(repoDir, branch);

  // Step 3: Commit files
  await commitFiles(repoDir, files);

  // Step 4: Push
  await pushBranch(repoDir, branch);

  // Step 5: Create PR
  const prUrl = await createPR(repoUrl, branch);

  // Step 6: Cleanup
  await cleanupRepo(jobId);

  return prUrl;
}
