// ENV Variable Builder

import { loadRegistry, getIntegration } from "./registry.js";

export function getEnvVarsForIntegrations(selected: string[]): string[] {
  const registry = loadRegistry();
  const vars = new Set<string>();

  for (const name of selected) {
    const integration = registry[name];
    if (integration?.env) {
      integration.env.forEach((v: string) => vars.add(v));
    }
  }

  return Array.from(vars);
}

export function generateEnvExample(selected: string[]): string {
  const registry = loadRegistry();
  const lines: string[] = [
    "# Auto-generated by AutoIntegrate",
    `# Integrations: ${selected.join(", ")}`,
    "",
  ];

  for (const name of selected) {
    const integration = registry[name];
    if (integration?.env && integration.env.length > 0) {
      lines.push(`# ${integration.name}`);
      for (const envVar of integration.env) {
        lines.push(`${envVar}=`);
      }
      lines.push("");
    }
  }

  return lines.join("\n");
}

export function generateEnvForIntegration(name: string): string {
  const integration = getIntegration(name);
  const lines: string[] = [`# ${integration.name}`, ""];

  if (integration.env) {
    for (const envVar of integration.env) {
      lines.push(`${envVar}=`);
    }
  }

  return lines.join("\n");
}

export function validateEnvVars(selected: string[]): {
  valid: boolean;
  missing: string[];
} {
  const required = getEnvVarsForIntegrations(selected);
  const missing = required.filter((v) => !process.env[v]);

  return {
    valid: missing.length === 0,
    missing,
  };
}

export function getEnvVarsByCategory(selected: string[]): Record<string, string[]> {
  const registry = loadRegistry();
  const byCategory: Record<string, string[]> = {};

  for (const name of selected) {
    const integration = registry[name];
    if (integration?.env) {
      const category = integration.category;
      if (!byCategory[category]) {
        byCategory[category] = [];
      }
      integration.env.forEach((v: string) => {
        if (!byCategory[category].includes(v)) {
          byCategory[category].push(v);
        }
      });
    }
  }

  return byCategory;
}
