// Pull Request Manager

import { Octokit } from "@octokit/rest";

export interface PRConfig {
  owner: string;
  repo: string;
  branch: string;
  base: string;
  title: string;
  body: string;
  token: string;
}

export interface PRResult {
  success: boolean;
  prUrl?: string;
  prNumber?: number;
  error?: string;
}

// Create a Pull Request
export async function createPullRequest(config: PRConfig): Promise<PRResult> {
  try {
    const client = new Octokit({ auth: config.token });

    console.log(`[PR] Creating PR: ${config.branch} -> ${config.base}`);

    const { data } = await client.pulls.create({
      owner: config.owner,
      repo: config.repo,
      head: config.branch,
      base: config.base,
      title: config.title,
      body: config.body,
    });

    console.log(`[PR] Created: ${data.html_url}`);

    return {
      success: true,
      prUrl: data.html_url,
      prNumber: data.number,
    };
  } catch (err: any) {
    console.error(`[PR] Failed to create PR:`, err.message);
    return {
      success: false,
      error: err.message,
    };
  }
}

// Add labels to PR
export async function addLabels(
  owner: string,
  repo: string,
  prNumber: number,
  labels: string[],
  token: string
): Promise<void> {
  const client = new Octokit({ auth: token });

  await client.issues.addLabels({
    owner,
    repo,
    issue_number: prNumber,
    labels,
  });

  console.log(`[PR] Added labels: ${labels.join(", ")}`);
}

// Add comment to PR
export async function addComment(
  owner: string,
  repo: string,
  prNumber: number,
  body: string,
  token: string
): Promise<void> {
  const client = new Octokit({ auth: token });

  await client.issues.createComment({
    owner,
    repo,
    issue_number: prNumber,
    body,
  });

  console.log(`[PR] Added comment to PR #${prNumber}`);
}

// Generate PR body
export function generatePRBody(integrations: string[], filesCount: number): string {
  return `
## 🚀 AutoIntegrate

This PR was automatically generated by **AutoIntegrate**.

### Integrations Added
${integrations.map((i) => `- \`${i}\``).join("\n")}

### Summary
- **Files added:** ${filesCount}
- **Generated at:** ${new Date().toISOString()}

### Next Steps
1. Review the generated code
2. Add your environment variables to \`.env.local\`
3. Install any required dependencies
4. Merge when ready!

---
*Powered by [AutoIntegrate](https://autointegrate.dev)*
`.trim();
}
