import { Octokit } from "@octokit/rest";
import { GITHUB_TOKEN, GITHUB_DEFAULT_BRANCH } from "../config.js";

export function getGitHubClient() {
  return new Octokit({ auth: GITHUB_TOKEN });
}

export async function createBranch(repo: string) {
  const gh = getGitHubClient();
  const [owner, name] = repo.split("/");

  const { data: repoData } = await gh.rest.repos.get({
    owner,
    repo: name
  });

  const { data: ref } = await gh.rest.git.getRef({
    owner,
    repo: name,
    ref: `heads/${repoData.default_branch}`
  });

  const branchName = GITHUB_DEFAULT_BRANCH;

  await gh.rest.git.createRef({
    owner,
    repo: name,
    ref: `refs/heads/${branchName}`,
    sha: ref.object.sha
  });

  return branchName;
}

export async function commitFiles(repo: string, files: { path: string; content: string }[]) {
  const gh = getGitHubClient();
  const [owner, name] = repo.split("/");

  // For each file, create or update
  for (const file of files) {
    try {
      // Try to get existing file
      const { data: existing } = await gh.rest.repos.getContent({
        owner,
        repo: name,
        path: file.path,
        ref: GITHUB_DEFAULT_BRANCH
      });

      await gh.rest.repos.createOrUpdateFileContents({
        owner,
        repo: name,
        path: file.path,
        message: `AutoIntegrate: Update ${file.path}`,
        content: Buffer.from(file.content).toString("base64"),
        branch: GITHUB_DEFAULT_BRANCH,
        sha: (existing as any).sha
      });
    } catch {
      // File doesn't exist, create it
      await gh.rest.repos.createOrUpdateFileContents({
        owner,
        repo: name,
        path: file.path,
        message: `AutoIntegrate: Add ${file.path}`,
        content: Buffer.from(file.content).toString("base64"),
        branch: GITHUB_DEFAULT_BRANCH
      });
    }
  }

  return { files: files.length };
}

export async function createPR(repo: string) {
  const gh = getGitHubClient();
  const [owner, name] = repo.split("/");

  const pr = await gh.rest.pulls.create({
    owner,
    repo: name,
    title: "AutoIntegrate Integration",
    head: GITHUB_DEFAULT_BRANCH,
    base: "main",
    body: "Automatically generated by AutoIntegrate."
  });

  return pr.data;
}

